### ISSUE TITLE
tracking issue for suggestions previously made on #7

### ISSUE THREAD

**Issue by TallTed** [w3c-ccg/vc-api-use-cases#10]
_Originally posted by @TallTed in https://github.com/w3c-ccg/vc-api-use-cases/issues/7#issuecomment-1149097531_

> @jandrieu -- Did you check whether the [label changes (and other minor tweaks)](https://github.com/w3c-ccg/vc-api-use-cases/pull/7#issuecomment-1116495940) I previously suggested ([1](https://github.com/w3c-ccg/vc-api-use-cases/pull/7#pullrequestreview-943423827), [2](https://github.com/w3c-ccg/vc-api-use-cases/pull/7#pullrequestreview-943424052)), which are only recorded here, had been made (by you or @eric-schuh) prior to merging this PR (which merge henceforth conceals my suggestions, unless carried to new issues/PRs)?

This is a tracking issue, to ensure the suggestions on #7 which I described above will be (if they have not already been) incorporated.

**Comment by eric-schuh** [comment]
The changes to the titles (having all the roles, e.g. "Holder" in parenthesis rather then after a dash) are all in the current 6 PRs, one for each use case. Let me know if you still would like any other format changes, moving from Visual Paradigm to Mermaid changed the look quite a bit.

Images are included with each PR
