### ISSUE TITLE
fixing mermaid white space

### ISSUE THREAD

**Issue by eric-schuh** [w3c-ccg/vc-api-use-cases#14]
@msporny what do we need to do to fix the mermaid white space issue for this repo?

**Comment by msporny** [comment]
> @msporny what do we need to do to fix the mermaid white space issue for this repo?

Just upgrading to the latest version of respec-mermaid should do it... 

```javascript
<script class="remove" src="https://cdn.jsdelivr.net/gh/digitalbazaar/respec-mermaid@1.0.1/dist/main.js"></script>
```

**Comment by eric-schuh** [comment]
Thanks, found that as you were responding I think, fixed in next PR
